import AstroChartCanvas from '@/shared/components/AstroChartCanvas'
import { ASTRO_PLANET_NAME, ASTRO_PLANET_SYMBOL } from '@/shared/configs/astro-planets.config'
import { ASTRO_PLANETS } from '@/shared/types/astro-planets'
const HOUSES = [
  128.324913, 144.869267, 166.419832, 196.431042, 236.64737, 277.408561, 308.324913, 324.869267, 346.419832,
  16.431042, 56.64737, 97.408561,
]
const PLANETS = [
  {
    name: 'Sun' as ASTRO_PLANETS,
    longitude: 290.875106,
    latitude: 0.00007360839586918036,
    distance: 0.9834198225768761,
    speed: 1.0188123662411863,
    isRetrograde: false,
  },
  {
    name: 'Moon' as ASTRO_PLANETS,
    longitude: 52.618048,
    latitude: -0.8984933129975592,
    distance: 0.0027084266999059087,
    speed: 11.771478139882586,
    isRetrograde: false,
  },
  {
    name: 'Mercury' as ASTRO_PLANETS,
    longitude: 307.271795,
    latitude: -1.6328942668781938,
    distance: 1.1652387354289162,
    speed: 1.5127907558808518,
    isRetrograde: false,
  },
  {
    name: 'Venus' as ASTRO_PLANETS,
    longitude: 244.030329,
    latitude: 3.5974942373193883,
    distance: 0.6587341915528389,
    speed: 1.0041525532145716,
    isRetrograde: false,
  },
  {
    name: 'Mars' as ASTRO_PLANETS,
    longitude: 152.173225,
    latitude: 3.861928980653029,
    distance: 0.7761540001697403,
    speed: -0.11491399943284933,
    isRetrograde: true,
  },
  {
    name: 'Jupiter' as ASTRO_PLANETS,
    longitude: 246.792355,
    latitude: 0.7613212979646915,
    distance: 6.040679691896474,
    speed: 0.1883781583172151,
    isRetrograde: false,
  },
  {
    name: 'Saturn' as ASTRO_PLANETS,
    longitude: 338.935274,
    latitude: -1.7801752028907825,
    distance: 10.307933421650349,
    speed: 0.09510673474107198,
    isRetrograde: false,
  },
  {
    name: 'Uranus' as ASTRO_PLANETS,
    longitude: 296.08965,
    latitude: -0.49565642075780303,
    distance: 20.672003486989173,
    speed: 0.058924559703064976,
    isRetrograde: false,
  },
  {
    name: 'Neptune' as ASTRO_PLANETS,
    longitude: 292.966552,
    latitude: 0.5494460970768087,
    distance: 31.156082583106144,
    speed: 0.03796654006208336,
    isRetrograde: false,
  },
  {
    name: 'Pluto' as ASTRO_PLANETS,
    longitude: 239.843923,
    latitude: 13.370240127397999,
    distance: 30.406794333336954,
    speed: 0.028167897646557014,
    isRetrograde: false,
  },
  {
    name: 'Proserpina' as ASTRO_PLANETS,
    longitude: 219.915159,
    latitude: 9.929982648271778e-7,
    distance: 79.54093080196606,
    speed: 0.005670012667200103,
    isRetrograde: false,
  },
  {
    name: 'Chiron' as ASTRO_PLANETS,
    longitude: 176.441863,
    latitude: -4.606064266822361,
    distance: 8.125925254216073,
    speed: -0.002341003478500341,
    isRetrograde: true,
  },
  {
    name: 'Lilith' as ASTRO_PLANETS,
    longitude: 60.983044,
    latitude: -1.7450084790434026,
    distance: 0.002710625131722547,
    speed: 0.11090556938503317,
    isRetrograde: false,
  },
  {
    name: 'Rahu' as ASTRO_PLANETS,
    longitude: 222.455194,
    latitude: 0,
    distance: 0.002399568934402188,
    speed: -0.02238491860133202,
    isRetrograde: true,
  },
  {
    name: 'Ketu' as ASTRO_PLANETS,
    longitude: 42.455194,
    latitude: 0,
    distance: 0.002399568934402188,
    speed: 0.02238491860133202,
    isRetrograde: true,
  },
  {
    name: 'Fortuna' as ASTRO_PLANETS,
    longitude: 6.581971,
    latitude: 0,
    distance: 1,
    speed: 0,
    isRetrograde: false,
  },
  {
    name: 'Selena' as ASTRO_PLANETS,
    longitude: 346.292,
    latitude: 0,
    distance: 1,
    speed: 0,
    isRetrograde: false,
  },
]
export const AstroDecodingPage = () => {
  const planets = PLANETS.map(({ name, longitude }) => ({
    name,
    label: ASTRO_PLANET_NAME[name],
    longitude,
    symbol: ASTRO_PLANET_SYMBOL[name] ?? ASTRO_PLANET_SYMBOL.Sun,
  }))

  return (
    <div>
      <AstroChartCanvas
        houseCusps={HOUSES}
        planets={planets}
        aspects={[
          {
            planetA: 'Moon',
            planetB: 'Neptune',
            aspectType: 'Trine',
            orb: 0.35,
            strength: 138.1,
            isExact: true,
            isVeryExact: true,
          },
          {
            planetA: 'Sun',
            planetB: 'Moon',
            aspectType: 'Trine',
            orb: 1.74,
            strength: 138,
            isExact: false,
            isVeryExact: true,
          },
          {
            planetA: 'Sun',
            planetB: 'Neptune',
            aspectType: 'Conjunction',
            orb: 2.09,
            strength: 110.9,
            isExact: false,
            isVeryExact: true,
          },
          {
            planetA: 'Jupiter',
            planetB: 'Fortuna',
            aspectType: 'Trine',
            orb: 0.21,
            strength: 101.9,
            isExact: true,
            isVeryExact: true,
          },
          {
            planetA: 'Venus',
            planetB: 'Jupiter',
            aspectType: 'Conjunction',
            orb: 2.76,
            strength: 90.4,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Proserpina',
            aspectType: 'Trine',
            orb: 0.98,
            strength: 90.3,
            isExact: true,
            isVeryExact: false,
          },
          {
            planetA: 'Moon',
            planetB: 'Uranus',
            aspectType: 'Trine',
            orb: 3.47,
            strength: 84.5,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Jupiter',
            aspectType: 'Sextile',
            orb: 0.48,
            strength: 83.2,
            isExact: true,
            isVeryExact: true,
          },
          {
            planetA: 'Venus',
            planetB: 'Mars',
            aspectType: 'Square',
            orb: 1.86,
            strength: 82.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Proserpina',
            planetB: 'Rahu',
            aspectType: 'Conjunction',
            orb: 2.54,
            strength: 81.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Uranus',
            planetB: 'Chiron',
            aspectType: 'Trine',
            orb: 0.35,
            strength: 80.8,
            isExact: true,
            isVeryExact: true,
          },
          {
            planetA: 'Pluto',
            planetB: 'Lilith',
            aspectType: 'Opposition',
            orb: 1.14,
            strength: 80.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mars',
            planetB: 'Lilith',
            aspectType: 'Square',
            orb: 1.19,
            strength: 76.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Fortuna',
            aspectType: 'Sextile',
            orb: 0.69,
            strength: 75.9,
            isExact: true,
            isVeryExact: false,
          },
          {
            planetA: 'Proserpina',
            planetB: 'Ketu',
            aspectType: 'Opposition',
            orb: 2.54,
            strength: 75,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Uranus',
            planetB: 'Neptune',
            aspectType: 'Conjunction',
            orb: 3.12,
            strength: 73.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Jupiter',
            planetB: 'Saturn',
            aspectType: 'Square',
            orb: 2.14,
            strength: 70.7,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Venus',
            planetB: 'Fortuna',
            aspectType: 'Trine',
            orb: 2.55,
            strength: 69.9,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Moon',
            planetB: 'Chiron',
            aspectType: 'Trine',
            orb: 3.82,
            strength: 68.7,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mars',
            planetB: 'Pluto',
            aspectType: 'Square',
            orb: 2.33,
            strength: 67.3,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Venus',
            planetB: 'Lilith',
            aspectType: 'Opposition',
            orb: 3.05,
            strength: 64.7,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Venus',
            planetB: 'Pluto',
            aspectType: 'Conjunction',
            orb: 4.19,
            strength: 63,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Proserpina',
            aspectType: 'Square',
            orb: 2.64,
            strength: 61.5,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Sun',
            planetB: 'Uranus',
            aspectType: 'Conjunction',
            orb: 5.21,
            strength: 52.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Rahu',
            aspectType: 'Trine',
            orb: 3.52,
            strength: 52.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Moon',
            planetB: 'Fortuna',
            aspectType: 'Semisquare',
            orb: 1.04,
            strength: 47.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Rahu',
            planetB: 'Selena',
            aspectType: 'Trine',
            orb: 3.84,
            strength: 45.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Neptune',
            planetB: 'Chiron',
            aspectType: 'Trine',
            orb: 3.48,
            strength: 42.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Sun',
            planetB: 'Jupiter',
            aspectType: 'Semisquare',
            orb: 0.92,
            strength: 41.1,
            isExact: true,
            isVeryExact: false,
          },
          {
            planetA: 'Moon',
            planetB: 'Pluto',
            aspectType: 'Opposition',
            orb: 7.23,
            strength: 39.1,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Venus',
            aspectType: 'Sextile',
            orb: 3.24,
            strength: 33.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Neptune',
            aspectType: 'Semisquare',
            orb: 0.97,
            strength: 32.2,
            isExact: true,
            isVeryExact: false,
          },
          {
            planetA: 'Jupiter',
            planetB: 'Neptune',
            aspectType: 'Semisquare',
            orb: 1.17,
            strength: 27.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Jupiter',
            planetB: 'Lilith',
            aspectType: 'Opposition',
            orb: 5.81,
            strength: 27.1,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mars',
            planetB: 'Jupiter',
            aspectType: 'Square',
            orb: 4.62,
            strength: 26.4,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Uranus',
            planetB: 'Lilith',
            aspectType: 'Trine',
            orb: 4.89,
            strength: 25.6,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Chiron',
            planetB: 'Rahu',
            aspectType: 'Semisquare',
            orb: 1.01,
            strength: 25.3,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Chiron',
            planetB: 'Ketu',
            aspectType: 'Sesquiquadrate',
            orb: 1.01,
            strength: 25.3,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Ketu',
            aspectType: 'Sextile',
            orb: 3.52,
            strength: 24.9,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Chiron',
            planetB: 'Lilith',
            aspectType: 'Trine',
            orb: 4.54,
            strength: 24.6,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Sun',
            planetB: 'Chiron',
            aspectType: 'Trine',
            orb: 5.57,
            strength: 22.6,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Pluto',
            planetB: 'Chiron',
            aspectType: 'Sextile',
            orb: 3.4,
            strength: 21.8,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Venus',
            planetB: 'Saturn',
            aspectType: 'Square',
            orb: 4.9,
            strength: 21,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Uranus',
            planetB: 'Pluto',
            aspectType: 'Sextile',
            orb: 3.75,
            strength: 19.9,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mars',
            planetB: 'Saturn',
            aspectType: 'Opposition',
            orb: 6.76,
            strength: 19.6,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Moon',
            planetB: 'Lilith',
            aspectType: 'Conjunction',
            orb: 8.36,
            strength: 19.5,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Ketu',
            planetB: 'Selena',
            aspectType: 'Sextile',
            orb: 3.84,
            strength: 18.6,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Sun',
            planetB: 'Venus',
            aspectType: 'Semisquare',
            orb: 1.84,
            strength: 17.7,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Jupiter',
            planetB: 'Pluto',
            aspectType: 'Conjunction',
            orb: 6.95,
            strength: 16.5,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Proserpina',
            planetB: 'Chiron',
            aspectType: 'Semisquare',
            orb: 1.53,
            strength: 16.5,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Rahu',
            aspectType: 'Square',
            orb: 5.18,
            strength: 15,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Ketu',
            aspectType: 'Square',
            orb: 5.18,
            strength: 15,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Selena',
            aspectType: 'Conjunction',
            orb: 7.36,
            strength: 10.1,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Mercury',
            planetB: 'Lilith',
            aspectType: 'Trine',
            orb: 6.29,
            strength: 9.7,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Proserpina',
            planetB: 'Selena',
            aspectType: 'Trine',
            orb: 6.38,
            strength: 8.9,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Sun',
            planetB: 'Selena',
            aspectType: 'Sextile',
            orb: 4.58,
            strength: 8.3,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Saturn',
            planetB: 'Uranus',
            aspectType: 'Semisquare',
            orb: 2.15,
            strength: 7.2,
            isExact: false,
            isVeryExact: false,
          },
          {
            planetA: 'Pluto',
            planetB: 'Fortuna',
            aspectType: 'Trine',
            orb: 6.74,
            strength: 3.7,
            isExact: false,
            isVeryExact: false,
          },
        ]}
      />
    </div>
  )
}
