import { ASTRO_ASPECT } from '@/shared/types/astro/astro-aspects.types'

const enum COLOR {
  GREEN = '#00FF7F',
  RED = '#FF073A',
  BLUE = '#1E90FF',
}

export const ASPECT_COLOR = {
  [ASTRO_ASPECT.CONJUCTION]: COLOR.BLUE,
  [ASTRO_ASPECT.OPPOSITION]: COLOR.RED,
  [ASTRO_ASPECT.TRINE]: COLOR.GREEN,
  [ASTRO_ASPECT.SQUARE]: COLOR.RED,
  [ASTRO_ASPECT.SEXTILE]: COLOR.GREEN,
  [ASTRO_ASPECT.QUINCUNX]: COLOR.GREEN,
}
