import { ASTRO_ZODIAC } from '../types/astro-zodiac'

export const ASTRO_ZODIAC_INDEX: Record<number, ASTRO_ZODIAC> = {
  1: ASTRO_ZODIAC.ARIES,
  2: ASTRO_ZODIAC.TAURUS,
  3: ASTRO_ZODIAC.GEMINI,
  4: ASTRO_ZODIAC.CANCER,
  5: ASTRO_ZODIAC.LEO,
  6: ASTRO_ZODIAC.VIRGO,
  7: ASTRO_ZODIAC.LIBRA,
  8: ASTRO_ZODIAC.SCORPIO,
  9: ASTRO_ZODIAC.SAGITTARIUS,
  10: ASTRO_ZODIAC.CAPRICORN,
  11: ASTRO_ZODIAC.AQUARIUS,
  12: ASTRO_ZODIAC.PISCES,
}

export const ASTRO_ZODIAC_NAME = {
  [ASTRO_ZODIAC.ARIES]: 'Овен',
  [ASTRO_ZODIAC.TAURUS]: 'Телец',
  [ASTRO_ZODIAC.GEMINI]: 'Близнецы',
  [ASTRO_ZODIAC.CANCER]: 'Рак',
  [ASTRO_ZODIAC.LEO]: 'Лев',
  [ASTRO_ZODIAC.VIRGO]: 'Дева',
  [ASTRO_ZODIAC.LIBRA]: 'Весы',
  [ASTRO_ZODIAC.SCORPIO]: 'Скорпион',
  [ASTRO_ZODIAC.SAGITTARIUS]: 'Стрелец',
  [ASTRO_ZODIAC.CAPRICORN]: 'Козерог',
  [ASTRO_ZODIAC.AQUARIUS]: 'Водолей',
  [ASTRO_ZODIAC.PISCES]: 'Рыбы',
}

export const ASTRO_ZODIAC_SYMBOL = {
  [ASTRO_ZODIAC.ARIES]: 'a',
  [ASTRO_ZODIAC.TAURUS]: 's',
  [ASTRO_ZODIAC.GEMINI]: 'd',
  [ASTRO_ZODIAC.CANCER]: 'f',
  [ASTRO_ZODIAC.LEO]: 'g',
  [ASTRO_ZODIAC.VIRGO]: 'h',
  [ASTRO_ZODIAC.LIBRA]: 'j',
  [ASTRO_ZODIAC.SCORPIO]: 'k',
  [ASTRO_ZODIAC.SAGITTARIUS]: 'l',
  [ASTRO_ZODIAC.CAPRICORN]: 'z',
  [ASTRO_ZODIAC.AQUARIUS]: 'x',
  [ASTRO_ZODIAC.PISCES]: 'c',
}
