import { ASTRO_PLANET } from '../types/astro/astro-planets.types'
import { ASTRO_ZODIAC, ASTRO_ZODIAC_ELEMENT, ASTRO_ZODIAC_MODALITY } from '../types/astro/astro-zodiac.types'

export const ASTRO_ZODIAC_INDEX: Record<number, ASTRO_ZODIAC> = {
  1: ASTRO_ZODIAC.ARIES,
  2: ASTRO_ZODIAC.TAURUS,
  3: ASTRO_ZODIAC.GEMINI,
  4: ASTRO_ZODIAC.CANCER,
  5: ASTRO_ZODIAC.LEO,
  6: ASTRO_ZODIAC.VIRGO,
  7: ASTRO_ZODIAC.LIBRA,
  8: ASTRO_ZODIAC.SCORPIO,
  9: ASTRO_ZODIAC.SAGITTARIUS,
  10: ASTRO_ZODIAC.CAPRICORN,
  11: ASTRO_ZODIAC.AQUARIUS,
  12: ASTRO_ZODIAC.PISCES,
}

export const ASTRO_ZODIAC_NAME: Record<ASTRO_ZODIAC, string> = {
  [ASTRO_ZODIAC.ARIES]: 'Овен',
  [ASTRO_ZODIAC.TAURUS]: 'Телец',
  [ASTRO_ZODIAC.GEMINI]: 'Близнецы',
  [ASTRO_ZODIAC.CANCER]: 'Рак',
  [ASTRO_ZODIAC.LEO]: 'Лев',
  [ASTRO_ZODIAC.VIRGO]: 'Дева',
  [ASTRO_ZODIAC.LIBRA]: 'Весы',
  [ASTRO_ZODIAC.SCORPIO]: 'Скорпион',
  [ASTRO_ZODIAC.SAGITTARIUS]: 'Стрелец',
  [ASTRO_ZODIAC.CAPRICORN]: 'Козерог',
  [ASTRO_ZODIAC.AQUARIUS]: 'Водолей',
  [ASTRO_ZODIAC.PISCES]: 'Рыбы',
}

export const ASTRO_ZODIAC_SYMBOL: Record<ASTRO_ZODIAC, string> = {
  [ASTRO_ZODIAC.ARIES]: 'a',
  [ASTRO_ZODIAC.TAURUS]: 's',
  [ASTRO_ZODIAC.GEMINI]: 'd',
  [ASTRO_ZODIAC.CANCER]: 'f',
  [ASTRO_ZODIAC.LEO]: 'g',
  [ASTRO_ZODIAC.VIRGO]: 'h',
  [ASTRO_ZODIAC.LIBRA]: 'j',
  [ASTRO_ZODIAC.SCORPIO]: 'k',
  [ASTRO_ZODIAC.SAGITTARIUS]: 'l',
  [ASTRO_ZODIAC.CAPRICORN]: 'z',
  [ASTRO_ZODIAC.AQUARIUS]: 'x',
  [ASTRO_ZODIAC.PISCES]: 'c',
}

export const ASTRO_ZODIAC_COLOR: Record<ASTRO_ZODIAC, string> = {
  [ASTRO_ZODIAC.ARIES]: '#FF6F49', // светлый кораллово-оранжевый
  [ASTRO_ZODIAC.TAURUS]: '#4CAF70', // свежий мягкий изумрудный
  [ASTRO_ZODIAC.GEMINI]: '#F7D94C', // светлый золотистый жёлтый
  [ASTRO_ZODIAC.CANCER]: '#5AA8FF', // светлый насыщенный голубой
  [ASTRO_ZODIAC.LEO]: '#F7A85A', // светлый и тёплый оранжевый
  [ASTRO_ZODIAC.VIRGO]: '#81D9B2', // нежный мятно-зелёный
  [ASTRO_ZODIAC.LIBRA]: '#B87EFF', // светлый фиолетовый с холодным оттенком
  [ASTRO_ZODIAC.SCORPIO]: '#D15757', // светлый тёплый красный (не яркий, но заметный)
  [ASTRO_ZODIAC.SAGITTARIUS]: '#4CA1FF', // яркий, но мягкий синий
  [ASTRO_ZODIAC.CAPRICORN]: '#6B7B8C', // светло-серый с синим оттенком
  [ASTRO_ZODIAC.AQUARIUS]: '#74D6F8', // яркий и светлый бирюзовый
  [ASTRO_ZODIAC.PISCES]: '#A979D1', // светлый пурпурный
}

export const ASTRO_ZODIAC_ELEMENT_NAME: Record<ASTRO_ZODIAC_ELEMENT, string> = {
  [ASTRO_ZODIAC_ELEMENT.FIRE]: 'Огонь',
  [ASTRO_ZODIAC_ELEMENT.AIR]: 'Воздух',
  [ASTRO_ZODIAC_ELEMENT.WATER]: 'Вода',
  [ASTRO_ZODIAC_ELEMENT.EARTH]: 'Земля',
}

export const ASTRO_ZODIAC_ELEMENT_SYMBOL: Record<ASTRO_ZODIAC_ELEMENT, string> = {
  [ASTRO_ZODIAC_ELEMENT.FIRE]: '🔥',
  [ASTRO_ZODIAC_ELEMENT.EARTH]: '🌱',
  [ASTRO_ZODIAC_ELEMENT.AIR]: '💨',
  [ASTRO_ZODIAC_ELEMENT.WATER]: '💧',
}

export const ASTRO_ZODIAC_MODALITY_NAME: Record<ASTRO_ZODIAC_MODALITY, string> = {
  [ASTRO_ZODIAC_MODALITY.CARDINAL]: 'Кардинальный',
  [ASTRO_ZODIAC_MODALITY.FIXED]: 'Фиксированный',
  [ASTRO_ZODIAC_MODALITY.MUTABLE]: 'Мутабельный',
}

export const ASTRO_ZODIAC_MODALITY_SYMBOL: Record<ASTRO_ZODIAC_MODALITY, string> = {
  [ASTRO_ZODIAC_MODALITY.CARDINAL]: '🚀',
  [ASTRO_ZODIAC_MODALITY.FIXED]: '⚖️',
  [ASTRO_ZODIAC_MODALITY.MUTABLE]: '🌀',
}

export const ASTRO_ZODIAC_SIGN_IN_ELEMENT: Record<ASTRO_ZODIAC, ASTRO_ZODIAC_ELEMENT> = {
  [ASTRO_ZODIAC.ARIES]: ASTRO_ZODIAC_ELEMENT.FIRE,
  [ASTRO_ZODIAC.TAURUS]: ASTRO_ZODIAC_ELEMENT.EARTH,
  [ASTRO_ZODIAC.GEMINI]: ASTRO_ZODIAC_ELEMENT.AIR,
  [ASTRO_ZODIAC.CANCER]: ASTRO_ZODIAC_ELEMENT.WATER,
  [ASTRO_ZODIAC.LEO]: ASTRO_ZODIAC_ELEMENT.FIRE,
  [ASTRO_ZODIAC.VIRGO]: ASTRO_ZODIAC_ELEMENT.EARTH,
  [ASTRO_ZODIAC.LIBRA]: ASTRO_ZODIAC_ELEMENT.AIR,
  [ASTRO_ZODIAC.SCORPIO]: ASTRO_ZODIAC_ELEMENT.WATER,
  [ASTRO_ZODIAC.SAGITTARIUS]: ASTRO_ZODIAC_ELEMENT.FIRE,
  [ASTRO_ZODIAC.CAPRICORN]: ASTRO_ZODIAC_ELEMENT.EARTH,
  [ASTRO_ZODIAC.AQUARIUS]: ASTRO_ZODIAC_ELEMENT.AIR,
  [ASTRO_ZODIAC.PISCES]: ASTRO_ZODIAC_ELEMENT.WATER,
}

export const ASTRO_ZODIAC_SIGN_IN_MODALITY: Record<ASTRO_ZODIAC, ASTRO_ZODIAC_MODALITY> = {
  [ASTRO_ZODIAC.ARIES]: ASTRO_ZODIAC_MODALITY.CARDINAL,
  [ASTRO_ZODIAC.TAURUS]: ASTRO_ZODIAC_MODALITY.FIXED,
  [ASTRO_ZODIAC.GEMINI]: ASTRO_ZODIAC_MODALITY.MUTABLE,
  [ASTRO_ZODIAC.CANCER]: ASTRO_ZODIAC_MODALITY.CARDINAL,
  [ASTRO_ZODIAC.LEO]: ASTRO_ZODIAC_MODALITY.FIXED,
  [ASTRO_ZODIAC.VIRGO]: ASTRO_ZODIAC_MODALITY.MUTABLE,
  [ASTRO_ZODIAC.LIBRA]: ASTRO_ZODIAC_MODALITY.CARDINAL,
  [ASTRO_ZODIAC.SCORPIO]: ASTRO_ZODIAC_MODALITY.FIXED,
  [ASTRO_ZODIAC.SAGITTARIUS]: ASTRO_ZODIAC_MODALITY.MUTABLE,
  [ASTRO_ZODIAC.CAPRICORN]: ASTRO_ZODIAC_MODALITY.CARDINAL,
  [ASTRO_ZODIAC.AQUARIUS]: ASTRO_ZODIAC_MODALITY.FIXED,
  [ASTRO_ZODIAC.PISCES]: ASTRO_ZODIAC_MODALITY.MUTABLE,
}

export const ASTRO_ZODIAC_RULER_PLANET: Record<ASTRO_ZODIAC, ASTRO_PLANET> = {
  [ASTRO_ZODIAC.ARIES]: ASTRO_PLANET.MARS,
  [ASTRO_ZODIAC.TAURUS]: ASTRO_PLANET.VENUS,
  [ASTRO_ZODIAC.GEMINI]: ASTRO_PLANET.MERCURY,
  [ASTRO_ZODIAC.CANCER]: ASTRO_PLANET.MOON,
  [ASTRO_ZODIAC.LEO]: ASTRO_PLANET.SUN,
  [ASTRO_ZODIAC.VIRGO]: ASTRO_PLANET.MERCURY,
  [ASTRO_ZODIAC.LIBRA]: ASTRO_PLANET.VENUS,
  [ASTRO_ZODIAC.SCORPIO]: ASTRO_PLANET.PLUTO, // можно выбрать Mars (традиционно) или Pluto (современно)
  [ASTRO_ZODIAC.SAGITTARIUS]: ASTRO_PLANET.JUPITER,
  [ASTRO_ZODIAC.CAPRICORN]: ASTRO_PLANET.SATURN,
  [ASTRO_ZODIAC.AQUARIUS]: ASTRO_PLANET.URANUS, // Saturn — традиционный
  [ASTRO_ZODIAC.PISCES]: ASTRO_PLANET.NEPTUNE, // Jupiter — традиционный
}
